# How often the application should check for updates (default: 30 seconds).
checkingInterval = { secs = 30, nanos = 0 }

# The day of the week to perform the signup check.
# Chrono can parse full day names ("Friday") or three-letter abbreviations ("Fri").
signupWeekday = "Thu"

# The day of the week the ride is happening.
rideWeekday = "Tue"

# The time of day (in UTC) to start checking, in HH:MM:SS format.
checkFrom = "17:30:00"

[strava]
# The numeric Strava club ID (visible in the club URL: strava.com/clubs/<clubId>).
clubId = ""

# A list of users to sign up for rides.
[[users]]
firstName = ""
surname = ""
email = ""
enabled = true
